# Generated by Django 2.1.3 on 2018-12-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='user',
        ),
    ]
